// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProjectPocoGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "ffa2775b-2540-4421-badd-0248d11914d8";
        public const string Name = "Provides abilities";
        public const string Description = @"Create POCO";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Jerry Nixon";
        public const string Tags = "dacpac, poco, dab";
    }
}
